### ISSUE TITLE
Fix missing projects and libraries icons

### ISSUE THREAD

**Issue by dominv** [47deg/org#60]
Some projects, like iota are not being shown in the https://47deg.github.io site and the freestyle's logo is not being shown either.

**Comment by dominv** [comment]
The site ,including the new changes, is not being deployed correctly https://travis-ci.org/47deg/org/builds/240313509

For what I've seen so far, the problem could be caused by this token https://github.com/47deg/org/blob/master/resources/config.edn#L44 that is used in https://github.com/47deg/org/blob/master/src/org/build.clj#L112

**Comment by dominv** [comment]
The error's stack trace:

```
Exception in thread "main" java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Don't know how to create ISeq from: java.util.concurrent.CompletableFuture, compiling:(/tmp/form-init6513735916646070472.clj:1:73)
	at clojure.lang.Compiler.load(Compiler.java:7442)
	at clojure.lang.Compiler.loadFile(Compiler.java:7368)
	at clojure.main$load_script.invokeStatic(main.clj:277)
	at clojure.main$init_opt.invokeStatic(main.clj:279)
	at clojure.main$init_opt.invoke(main.clj:279)
	at clojure.main$initialize.invokeStatic(main.clj:310)
	at clojure.main$null_opt.invokeStatic(main.clj:344)
	at clojure.main$null_opt.invoke(main.clj:341)
	at clojure.main$main.invokeStatic(main.clj:423)
	at clojure.main$main.doInvoke(main.clj:386)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
Caused by: java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Don't know how to create ISeq from: java.util.concurrent.CompletableFuture
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895)
	at clojure.core$deref_future.invokeStatic(core.clj:2290)
	at clojure.core$deref.invokeStatic(core.clj:2310)
	at clojure.core$deref.invoke(core.clj:2296)
	at org.build$fetch_data_BANG_.invokeStatic(build.clj:111)
	at org.build$fetch_data_BANG_.invoke(build.clj:111)
	at org.build$generate_site_BANG_.invokeStatic(build.clj:132)
	at org.build$generate_site_BANG_.invoke(build.clj:130)
	at org.build$_main.invokeStatic(build.clj:151)
	at org.build$_main.doInvoke(build.clj:145)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.Var.invoke(Var.java:375)
	at user$eval26705.invokeStatic(form-init6513735916646070472.clj:1)
	at user$eval26705.invoke(form-init6513735916646070472.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6978)
	at clojure.lang.Compiler.eval(Compiler.java:6968)
	at clojure.lang.Compiler.load(Compiler.java:7430)
	... 12 more
Caused by: java.lang.IllegalArgumentException: Don't know how to create ISeq from: java.util.concurrent.CompletableFuture
	at clojure.lang.RT.seqFrom(RT.java:547)
	at clojure.lang.RT.seq(RT.java:527)
	at clojure.core$seq__6422.invokeStatic(core.clj:137)
	at clojure.core$map$fn__6881.invoke(core.clj:2719)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.RT.seq(RT.java:525)
	at clojure.core$seq__6422.invokeStatic(core.clj:137)
	at clojure.core$seq__6422.invoke(core.clj:137)
	at urania.core$collect.invokeStatic(core.cljc:152)
	at urania.core$collect.invoke(core.cljc:148)
	at urania.core$traverse$fn__28923.invoke(core.cljc:161)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:657)
	at clojure.core$apply.invoke(core.clj:652)
	at urania.core.FlatMap._inject(core.cljc:78)
	at urania.core$inject_into.invokeStatic(core.cljc:117)
	at urania.core$inject_into.invoke(core.cljc:114)
	at clojure.core$partial$fn__6855.invoke(core.clj:2597)
	at clojure.core$map$fn__6881.invoke(core.clj:2728)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.RT.seq(RT.java:525)
	at clojure.core$seq__6422.invokeStatic(core.clj:137)
	at clojure.core$every_QMARK_.invokeStatic(core.clj:2652)
	at clojure.core$every_QMARK_.invoke(core.clj:2645)
	at urania.core.Map._inject(core.cljc:58)
	at urania.core$inject_into.invokeStatic(core.cljc:117)
	at urania.core$inject_into.invoke(core.cljc:114)
	at urania.core$interpret_ast.invokeStatic(core.cljc:221)
	at urania.core$interpret_ast.invoke(core.cljc:219)
	at urania.core$interpret_ast$fn__28964.invoke(core.cljc:233)
	at promesa.impl.promise$eval28329$fn$reify__28335.apply(promise.cljc:97)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:443)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by dominv** [comment]
Already solved updating the funcool/promesa library and setting a new github api key
